language: elixir

elixir:
  - 1.8.2

addons:
  postgresql: '11.2'

services:
  - postgresql

before_script:
  - psql -c 'create database elixir_test;' -U postgres
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate

script:
  - mix test
