language: elixir

elixir:
  - 1.8.2

otp_release: "20.1"

addons:
  postgresql: '11.2'

services:
  - postgresql: '9.6'

env:
  - MIX_ENV=test

before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.setup

script:
  - mix test
